export const appRoutes = {
  overview: '/',
  modernPrototype: '/prototype',
  agentAccess: '/access/agents',
  sceneManagement: '/access/scenes',
  credentialManagement: '/access/credentials',
  ingestion: '/ingestion',
  dataValidation: '/ingestion/validation',
  memory: '/memory',
  userMemory: '/memory/user',
  sessionMemory: '/memory/session',
  taskMemory: '/memory/task',
  retrieval: '/retrieval',
  semanticRetrieval: '/retrieval/semantic',
  keywordRetrieval: '/retrieval/keyword',
  metadataRetrieval: '/retrieval/metadata',
  fusionRetrieval: '/retrieval/fusion',
  topKRetrieval: '/retrieval/top-k',
  generation: '/generation',
  context: '/context',
  jsonContext: '/context/json',
  textContext: '/context/text',
  relevanceContext: '/context/relevance',
  lengthContext: '/context/length',
  task: '/task',
  monitoring: '/monitoring',
  healthMonitoring: '/monitoring/health',
  callsMonitoring: '/monitoring/calls',
  recordsMonitoring: '/monitoring/records',
  settings: '/settings',
  connectionSettings: '/settings/connection',
  identitySettings: '/settings/identity',
} as const

export type AppRoutePath = (typeof appRoutes)[keyof typeof appRoutes]
